# site settings
title: Vowei
subtitle: by Solar Development
email: info@voweisolar.com
description: <br /> el cambio a la energía renovable, sostenible, limpia, ecológica, <b>barata</b>, y disponible.
baseurl: "/vowei" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Calle la Comunicación, 7
city: Azuqueca de Henares
state: Guadalajara
zip_code: 19200
country: España
phone: (+34) 637287891

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://www.facebook.com/voweisolar/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
